### ISSUE TITLE
Cannot get jackett working

### ISSUE THREAD

**Issue by adocampo** [BoredLama/stremio-jackett-local#1]
I've posted this issue on [PMS' repo](https://github.com/sungshon/PimpMyStremio/issues/84), but this seems to be the right place to post in, so here we go!

I have a docker container on my home server with jackett, transmission, medusa, and plex, so it downloads everything I want just perfect, but I would like to see "on demand" those torrents through stremio. 

On my PC, I've installed PMS, and configured jackett addon like this:
![image](https://user-images.githubusercontent.com/2266612/93649477-62102c00-fa0c-11ea-810c-e062b43c9ade.png)

On the output I see the addon is loaded on PMS
```
$ ./PimpMyStremio 
PimpMyStremio - Checking for updates
PimpMyStremio - Already have latest version
PimpMyStremio - User defined add-ons list URL is valid, updating add-ons list
PimpMyStremio - Successfully updated add-ons list from remote source
Remote access choice: No (local)
Add-on running: BoredLama/stremio-jackett-local
PimpMyStremio server running at: http://127.0.0.1:7777
systrayhelper 0.0.5 (d5794e2a72a9cb160d78b6fd9ee640ad1df02af7 built 2018-12-05T09:24:55Z)
```

Then, copied the Addon URL (http://127.0.0.1:7777/stremio-jackett-local/manifest.json) and pasted on "Play URL/Magnet link"
![image](https://user-images.githubusercontent.com/2266612/93649570-9388f780-fa0c-11ea-8778-dabb21385639.png)
I click on "Install"
![image](https://user-images.githubusercontent.com/2266612/93650287-689fa300-fa0e-11ea-9b54-a8814b71a958.png)
And I can see it on my installed addons
![image](https://user-images.githubusercontent.com/2266612/93650326-83721780-fa0e-11ea-92c2-e562735eb9bc.png)

So, let's do some test. First I did a search on Jackett, to see there are results
![image](https://user-images.githubusercontent.com/2266612/93650425-bfa57800-fa0e-11ea-855e-ddf265e16ed5.png)

And search for the same tv show on stremio, and select any episode, then the message ADD-ON JACKETT IS STILL LOADING appears
![image](https://user-images.githubusercontent.com/2266612/93650513-ff6c5f80-fa0e-11ea-956d-9ad7911a454f.png)

I wait then until the message disappears, but no jackett source appears to select from... 

Finally, that after waiting for loading Jackett add-on, then it stops on PMS
![image](https://user-images.githubusercontent.com/2266612/93651744-e2d22680-fa12-11ea-84de-574c53b0e34b.png)
Log shows
```
Add-on stopped: BoredLama/stremio-jackett-local
stremio-jackett-local - add-on was stopped for taking longer then 2 mins to answer a request
```
I'm doing anything wrong? How can I see what's happening? Do I need to run jackett on the same host as PMS and Stremio?

Thank you!

**Comment by adocampo** [comment]
Reviewing the issue I've noticed jackett reports number of seeds incorrectly, and it always says there are just one seed, which isn't true. I've changed the default settings on jackett add-on to 1 minimum seed and now it's working
![image](https://user-images.githubusercontent.com/2266612/93719792-2187ee00-fb85-11ea-9f2a-f006aed9fb16.png)

![image](https://user-images.githubusercontent.com/2266612/93719825-62800280-fb85-11ea-946e-956eda9b7502.png)

But I noticed it doesn't return all the results, on the screenshot above it returns results just from Elitetorrent and NewPCT, but as you can see, there is also results for two sites more, DivxTotal
![image](https://user-images.githubusercontent.com/2266612/93719912-f356de00-fb85-11ea-8ca4-225562cafb66.png)
and MejorTorrent
![image](https://user-images.githubusercontent.com/2266612/93719940-27ca9a00-fb86-11ea-8334-3037c0852047.png)
And torrents are indeed alive and working
![image](https://user-images.githubusercontent.com/2266612/93719977-606a7380-fb86-11ea-9391-8e5816e44be9.png)

I don't know if you want me to open another issue for this last behavior.

**Comment by BoredLama** [comment]
I think Jackett might show 1 seed if it is unable to get the seed count from the website, I guess maintaining so many trackers might have it's faults..

This addon removes duplicate torrents, the same exact torrent (same infohash) can be on multiple websites (but the trackers might be different), this is why you might not see some of the results.

I guess I could set the default min seeds to 1 in order to ensure this doesn't happen again, and look into why it hangs when it has no results.. but in order to get the seed count fixed, it would need to be reported at Jackett's own repo for each website that doesn't work.

**Comment by BoredLama** [comment]
btw, the response time, min seeds, max seeds, req open timeout, req resp timeout, if set to `0` disables them completely, so you don't need to set extremely high values for them. Setting min seeds to `1` should also show the torrents with 1 seed, because it's filtering by higher or equal to.

**Comment by adocampo** [comment]
Cool, I let all timeouts to 0 and now it seems it returns results way faster.
Regarding the missing results, it seems so, I saw those other missing websites on other searches. I have to test it more in deep, but so far is working quite well.

**Comment by voron0021** [comment]
Please help me connect the jackett? If you can throw off the step-by-step instructions?
